### ISSUE TITLE
Am I starting it the wrong way?

### ISSUE THREAD

**Issue by NoclubOIRzXx** [IN2-Moist/2Take1-Moist-Script#11]
![image](https://user-images.githubusercontent.com/40497676/225938599-01542bf1-9aa4-484d-964f-5ef8770ce6f4.png)

[2023-03-17 22:49:32] [Lua Script] MoistScript_NextGen3012.luac has been executed.
[2023-03-17 22:49:32] [Safe Mode Enabled!] Script Events will no longer work on you if you try
[2023-03-17 22:49:33] [Lua Exception] [Failed to resume coroutine] ...aming\PopstarDevs\2Take1Menu\scripts\MoistFiles\json.lua:187: unexpected character '' at line 1 col 1
stack traceback:
	[C]: in function 'error'
	...aming\PopstarDevs\2Take1Menu\scripts\MoistFiles\json.lua:187: in function 'decode_error'
	...aming\PopstarDevs\2Take1Menu\scripts\MoistFiles\json.lua:373: in upvalue 'parse'
	...aming\PopstarDevs\2Take1Menu\scripts\MoistFiles\json.lua:381: in field 'decode'
	?: in field 'VersionWebCheck'
	?: in function <?:99>

**Comment by IN2-Moist** [comment]
@NoclubOIRzXx 
not sure whats going on there tht can happen with http trust not being enabled but there is a check for that.
could be an issue with accessing the url, hard to say with json library it errors out whenever it did not receive the expected data.
so a Error code return or some garbage text in the return could do this.
Try the latest version see if you still have any issue

**Comment by IN2-Moist** [comment]
No further innformtion received so will assume this is not an issue any more.
Feel Free to post again should that not be the case thanks.
