### ISSUE TITLE
I encountered the same issue again.

### ISSUE THREAD

**Issue by NoclubOIRzXx** [IN2-Moist/2Take1-Moist-Script#13]
Version：[MoistScript NG 3.0.2.2](https://github.com/IN2-Moist/2Take1-Moist-Script/releases/tag/3.0.2.2)

![image](https://github.com/IN2-Moist/2Take1-Moist-Script/assets/40497676/1d9bee9d-95f5-4a0b-a71f-8f2333c91ce8)

Even a complete uninstall and reinstall didn't work.
This issue didn't occur in MoistScript NextGen 3.0.2.0 Bug Fix 2 version.

![image](https://github.com/IN2-Moist/2Take1-Moist-Script/assets/40497676/2d8c9c14-b45a-4826-aaa2-7c09153b9732)

Even after uninstalling, it always shows "Checking for new version" in the bottom right corner.

**Comment by IN2-Moist** [comment]
> Version：[MoistScript NG 3.0.2.2](https://github.com/IN2-Moist/2Take1-Moist-Script/releases/tag/3.0.2.2)
> 
> ![image](https://user-images.githubusercontent.com/40497676/238013106-1d9bee9d-95f5-4a0b-a71f-8f2333c91ce8.png)
> 
> Even a complete uninstall and reinstall didn't work. This issue didn't occur in MoistScript NextGen 3.0.2.0 Bug Fix 2 version.
> 
> ![image](https://user-images.githubusercontent.com/40497676/238014410-2d8c9c14-b45a-4826-aaa2-7c09153b9732.png)
> 
> Even after uninstalling, it always shows "Checking for new version" in the bottom right corner.

There was an issue with update feature causing random crashes. The  error your showing is like there is an error accessing the site, can you directly access [updatehashed.json](https://raw.githubusercontent.com/IN2-Moist/2Take1-Moist-Script/main/updatehashed.json) ?

**Comment by IN2-Moist** [comment]
@NoclubOIRzXx 
Does this only happen after you have run the translation script to translate it all?
wondering if name changes could even be an issue since some stuff uses the english names

**Comment by IN2-Moist** [comment]
These issues should now be resolved in **3.0.3.4**
Please dont hesitate to post again should this issue not be resolved or it comes back.
a threaded Protected call to these features is now implemented so should resolve these update issues

**Comment by IN2-Moist** [comment]
These issues should now be resolved in **3.0.3.4**
Please dont hesitate to post again should this issue not be resolved or it comes back.
a threaded Protected call to these features is now implemented so should resolve these update issues
