### ISSUE TITLE
Enabling MK2 Rapid Fire or Set MK2 Machine Guns Only causes a crash

### ISSUE THREAD

**Issue by dotprofile** [IN2-Moist/2Take1-Moist-Script#2]
If I enable these options on myself, it causes an immediate crash. I discovered this as I like to test stuff on myself before I do so on others. Reproduction is as simple as it sounds. Unless enabling all protections on myself causes the issue, I don't seem to have anything enabled that would cause this.

**Comment by IN2-Moist** [comment]
> If I enable these options on myself, it causes an immediate crash. I discovered this as I like to test stuff on myself before I do so on others. Reproduction is as simple as it sounds. Unless enabling all protections on myself causes the issue, I don't seem to have anything enabled that would cause this.

Thanks i will look into this, by default hotkey enabled Rapid fire should be used on self. Provide more details if you could, were both turned on at the same time?

Soon as i have finished testing and fixing the code on the major update im working on i will push a new version, currently working out the bugs produced by the alterations to make the script function in a new way.

**Comment by IN2-Moist** [comment]
#2 Enabling MK2 Rapid Fire or Set MK2 Machine Guns Only causes a crash 
@dotprofile 
are you using any other scripts along side of this one?
i can not replicate this in my current edit, tried turning all on same time, no crash no lag worked fine
if you could give any more details would be appreciated

**Comment by IN2-Moist** [comment]
Since releasing a new build and not being able to replicate this or had any further reply or comments on this i will assume this is fixed and issue closed thanks
