### ISSUE TITLE
Hi , can you add language option in the script

### ISSUE THREAD

**Issue by chenchen94500** [IN2-Moist/2Take1-Moist-Script#3]
Can you add language system inside the script so we can add translate for option to the language we want ( i can translate option for you )

**Comment by IN2-Moist** [comment]
ok that could be more complex but if you would like to do the translation could look at doing a version targeted just for the language you want

**Comment by IN2-Moist** [comment]
@chenchen94500 Translation can be done by anyone!

So if you load my script then go to the menu Local tab and settings
locate Save lang.ini and click on it
this will save a file "lang.ini" here: `%UserProfile%\AppData\Roaming\PopstarDevs\2Take1Menu`
you will find all the script functions in here translate them save reinject the menu and the menu and script will all be translated.
i will look at running this through some online translator and include them if i can at some point online translator is not always great at its job XD even more so i think with some of the function names so i will do some function name updates too

**Comment by kiccer** [comment]
This `lang.ini` file will also contain the names of many other players, as well as some organization names, and it's too complicated to exclude these items and then translate others!
