### ISSUE TITLE
Escord Ped in vehicle

### ISSUE THREAD

**Issue by Aronax79** [IN2-Moist/2Take1-Moist-Script#5]
when i m spawning a escort ped in a vehicle he isn't following even if i push the "escort vehicle follow" button, idk if im doing smth wrong

**Comment by IN2-Moist** [comment]
Escorts that follow from what i remember need you to be in a vehicle to work
set ped
set vehicle
create ped
create vehicle set ped inside
then hit one of the tasks:
escort
wander
drive me
etc
some require to update task when changing or setting stuff more so for the ones that they drive you around

Give that a go see if you still have the issue
i will be making an improved version in the next gen release soon
