### ISSUE TITLE
Moist Script Loader - double Scripts

### ISSUE THREAD

**Issue by mgavdhout** [IN2-Moist/2Take1-Moist-Script#7]
When i check Moists Script Loader i have TWICE the 2Take1Script.lua at the top of the list. And I am sure that in the Script Folder there is only ONE 2Take1Script.lua. (I double checked also possible 'hidden' files, but there is not any.

![image](https://user-images.githubusercontent.com/96773003/170232355-82d6a909-6ec5-404e-990b-a010bc7272ce.png)

**Comment by IN2-Moist** [comment]
Not noticed this but will look to see what the issue could be when i rewrite for the next gen version
